name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  functions_lint:
    name: functions/lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn run lint

  functions_build:
    name: functions/build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn run build

  front_lint:
    name: front/lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn run lint

  front_build:
    name: front/build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn run build
